Skip if download failed and support manual dispatch

diff --git a/.github/workflows/mirror-mattoco-all-country-rate.yaml b/.github/workflows/mirror-mattoco-all-country-rate.yaml
--- a/.github/workflows/mirror-mattoco-all-country-rate.yaml
+++ b/.github/workflows/mirror-mattoco-all-country-rate.yaml
@@ -6,6 +6,7 @@ on:
     - main
   schedule:
   - cron: '0 17 * * *' # daily deploy at 2 am JST
+  workflow_dispatch:
 
 jobs:
   mirror:
@@ -16,7 +17,11 @@ jobs:
       uses: actions/checkout@v4
 
     - name: Download file
-      run: curl -O https://emaxis.am.mufg.jp/fund_file/chart/chart_data_253425.js
+      run: |
+        if ! curl --fail -O https://emaxis.am.mufg.jp/fund_file/chart/chart_data_253425.js; then
+          echo "Download failed, exiting."
+          exit 0
+        fi
 
     - uses: google-github-actions/auth@v2
       with:
